---
version: '3'
x-reinforcement: &reinforcement-common-build
  image: reinforcement
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    DISPLAY: $DISPLAY
    QT_X11_NO_MITSHM: 1
    DATA_DIR: /data/
  volumes:
    - ./logs:/data/logs
    - ./pretrained:/data/pretrained
    - /tmp/.X11-unix/:/tmp/.X11-unix/

services:
  custom:
    <<: *reinforcement-common-build
    container_name: reinforcement-custom
  discrete-play-q:
    <<: *reinforcement-common-build
    container_name: reinforcement-discrete-play-q
    command: python3 reinforcement/main.py discrete play --render --pretrained FrozenLake_q_learning.npz
  discrete-play-sarsa:
    <<: *reinforcement-common-build
    container_name: reinforcement-discrete-play-sarsa
    command: python3 reinforcement/main.py discrete play --render --pretrained FrozenLake_sarsa.npz
  continuous-play-simple:
    <<: *reinforcement-common-build
    container_name: reinforcement-continuous-play-simple
    command: python3 reinforcement/main.py continuous play --render --pretrained CarRacing_Simple.pth
  continuous-play-complex:
    <<: *reinforcement-common-build
    command: python3 reinforcement/main.py continuous play --render --pretrained CarRacing_Complex.pth

